### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by ChaoyiXie** [DarlingHang/st-nerf#4]
>>python demo/taekwondo_demo.py -c configs/config_taekwondo.yml
Traceback (most recent call last):
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\egl.py", line 67, in EGL
    return ctypesloader.loadLibrary(
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "D:\D\anaconda\envs\st-nerf\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: ("Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/taekwondo_demo.py", line 23, in <module>
    from render import LayeredNeuralRenderer
  File ".\render\__init__.py", line 4, in <module>
    from .neural_renderer import NeuralRenderer
  File ".\render\neural_renderer.py", line 9, in <module>
    from .bkgd_renderer import PrRender
  File ".\render\bkgd_renderer.py", line 7, in <module>
    import pyrender as pr
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\D\anaconda\envs\st-nerf\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

platform: win10

**Comment by Jiakai-Zhang** [comment]
You have to install EGL library for off-screen rendering

**Comment by ChaoyiXie** [comment]
> You have to install EGL library for off-screen rendering

run pip install EGL
then still have the same error, how to install EGL library on win10 platform

**Comment by Jiakai-Zhang** [comment]
> > You have to install EGL library for off-screen rendering
> 
> run pip install EGL
> then still have the same error, how to install EGL library on win10 platform

I guess there should be something wrong with your PATH environment, what you are missing is a system-level library instead of a python package. We are using ubuntu so we can just run apt install to fix the similar problem, I am sorry that I cannot help you further.
